# Generated by Django 5.2.8 on 2025-11-15 10:05

from django.db import migrations, models


def ensure_single_super_admin(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    super_admins = User.objects.filter(admin_type='super_admin').order_by('id')

    if super_admins.count() <= 1:
        return

    keeper = super_admins.first()
    extras = super_admins.exclude(pk=keeper.pk)

    for user in extras:
        user.admin_type = 'admin'
        if user.status != 'suspended':
            user.status = 'pending_approval'
        user.save(update_fields=['admin_type', 'status'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending_approval', 'Pending Approval'), ('suspended', 'Suspended')], default='pending_approval', help_text='Workflow status controlling dashboard access.', max_length=20),
        ),
        migrations.RunPython(ensure_single_super_admin, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='admin_type',
            field=models.CharField(blank=True, choices=[('super_admin', 'Super Admin'), ('admin', 'Admin')], help_text='Role assigned to the user within the admin workflow.', max_length=20, null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('admin_type', 'super_admin')), fields=('admin_type',), name='unique_super_admin_user'),
        ),
    ]
