# Generated by Django 5.2.8 on 2025-11-16 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_video', models.FileField(blank=True, help_text='Hero section background video', null=True, upload_to='landing/hero/')),
                ('logo_light', models.ImageField(blank=True, help_text='Logo for light mode', null=True, upload_to='landing/logos/')),
                ('logo_dark', models.ImageField(blank=True, help_text='Logo for dark mode', null=True, upload_to='landing/logos/')),
                ('contact_phone', models.CharField(blank=True, default='+44 (0) 20 1234 5678', help_text='Contact phone number', max_length=50)),
                ('contact_email', models.EmailField(blank=True, default='info@prestigecarhire.co.uk', help_text='Contact email address', max_length=254)),
                ('contact_address', models.CharField(blank=True, default='London, United Kingdom', help_text='Contact address', max_length=255)),
                ('contact_hours', models.CharField(blank=True, help_text="Business hours (e.g., 'Monday - Friday: 9:00 AM - 6:00 PM')", max_length=255)),
                ('google_map_embed_url', models.TextField(blank=True, help_text="Google Maps embed URL or iframe code for 'Visit Our Office' section")),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Landing Page Configuration',
                'verbose_name_plural': 'Landing Page Configurations',
            },
        ),
    ]
