# Generated by Django 5.2.8 on 2025-11-20 19:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('intro', 'Chatbot Introduction'), ('company', 'Company Information'), ('services', 'Services Overview'), ('working', 'How We Work'), ('faqs', 'Frequently Asked Questions'), ('pricing', 'Pricing Information'), ('contact', 'Contact Details'), ('policies', 'Company Policies'), ('emergency', 'Emergency Services')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='Detailed context content for this section')),
                ('keywords', models.TextField(blank=True, help_text='Comma-separated keywords for intent classification')),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot Context',
                'verbose_name_plural': 'Chatbot Contexts',
                'ordering': ['display_order', 'section'],
            },
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=200, unique=True)),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user_name', models.CharField(blank=True, max_length=200)),
                ('user_phone', models.CharField(blank=True, max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_lead', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('manual', 'Manual Reply Active')], default='active', max_length=20)),
                ('manual_reply_active', models.BooleanField(default=False)),
                ('collected_data', models.JSONField(default=dict, help_text='Extracted data from conversation')),
                ('intent_classification', models.CharField(blank=True, max_length=100)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='chatbot_con_status_aad5f3_idx'), models.Index(fields=['session_id'], name='chatbot_con_session_6c660a_idx'), models.Index(fields=['ip_address'], name='chatbot_con_ip_addr_c71d8c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('assistant', 'Assistant Message (AI)'), ('admin', 'Admin Message (Manual)')], default='user', max_length=20)),
                ('content', models.TextField()),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_admin_reply', models.BooleanField(default=False, help_text='True if this is a manual admin reply')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chatbot.conversation')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
    ]
