# Generated by Django 5.2.8 on 2025-11-22 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotSettings',
            fields=[
                ('id', models.IntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('api_key', models.CharField(blank=True, help_text='Groq API Key (leave empty to use environment variable GROQ_API_KEY)', max_length=500)),
                ('model', models.CharField(choices=[('mixtral-8x7b-32768', 'Mixtral 8x7B (32K context)'), ('llama-3.1-70b-versatile', 'Llama 3.1 70B Versatile'), ('llama-3.1-8b-instant', 'Llama 3.1 8B Instant'), ('gemma-7b-it', 'Gemma 7B IT'), ('llama-3.2-90b-text-preview', 'Llama 3.2 90B Text Preview')], default='mixtral-8x7b-32768', help_text='LLM model to use for chatbot responses', max_length=100)),
                ('max_tokens', models.IntegerField(default=500, help_text='Maximum tokens for AI responses')),
                ('temperature', models.FloatField(default=0.7, help_text='Temperature for AI responses (0.0-2.0, higher = more creative)')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable chatbot functionality')),
                ('auto_populate_context', models.BooleanField(default=True, help_text='Automatically populate default contexts on startup')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chatbot_settings_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chatbot Settings',
                'verbose_name_plural': 'Chatbot Settings',
            },
        ),
    ]
